let id = 0;

const location = [
  "Auckland",
  "Wellington",
  "Northland",
  "Manawatu - Wanganui",
  "Tauranga",
  "Rotorua - Taupo",
  "Hawkes Bay",
  "Christchurch",
  "Taranaki",
  "Nelson - Malborough",
  "Queenstown - Wanaka",
  "Dunedin - Invercargill",
];

const category = [
  "Activities-events-outdoors",
  "Automotive",
  "Baby-kids-toys",
  "Beauty-massage-spa",
  "Books-magazines",
  "Clothing-fashion-men",
  "Clothing-fashion-women",
  "Collections",
  "Electronics-computers",
  "Escapes",
  "Featured Auckland Deals",
  "Fitness-sports",
  "Grocery-food",
  "Health-nutrition-dental",
  "Holidays-hotels-travel",
  "House-garden",
  "Pets",
  "Restaurants-bars-cafes",
  "Stationery-art-craft",
  "Store",
  "Training-courses",
  "Weddings-special-occasions-parties",
  "Wine-beer-spirits",
];

const merchandise = [
  {
    id: id++,
    Title: "Inclusive Hanmer Springs Gateway",
    Category: category[10],
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga ab sapiente quidem doloremque voluptates explicabo accusamus alias quod consequatur ipsa ex aliquid quisquam eveniet id, id++tque totam officiis obcaecati sed?",
    Price: 420,
    AfterDiscount: 189,
    Provider: "Hanmer Springs Hotel",
    City: location[7],
    BuyingTimes: 304,
    FreeDelivery: false,
    IsNew: false,
    Image:
      "https://main-cdn.grabone.co.nz/goimage/fullsize/d3162da6dbd501bca97675ef50ed44b23cffd04f.jpg",
  },
  {
    id: id++,
    Title: "Mesh Reusable Face Mask",
    Category: category[10],
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus veritatis obcaecati odit placeat, minima et facilis ab eum harum alias, ratione dolorem voluptas nesciunt ea animi, distinctio quaerat voluptatum in?",
    Price: 9,
    AfterDiscount: null,
    Provider: null,
    City: null,
    BuyingTimes: 68,
    FreeDelivery: false,
    IsNew: false,
    Image:
      "https://main-cdn.grabone.co.nz/goimage/fullsize/32286725841603f9c33fc6257a8b797d24738be8.jpg",
  },
  {
    id: id++,
    Category: category[10],
    Image: "https://mediacdn.grabone.co.nz/asset/07BDTi7qVy",
    IsNew: false,
    Title: "Grocery Goodies",
    Provider: "Multiple deals",
    City: null,
    BuyingTimes: "",
    price: "",
    button: true,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/c1a3dbabdbba0721012652889951780c340c30bd.jpg",
    IsNew: false,
    Title:
      "Two Silver Fern Farms New Zealand Export-Quality Beef Tenderloin Eye Fillets (1.8 - 2.2kg per Slab)",
    Provider: "",
    City: null,
    BuyingTimes: "",
    price: 180,
    button: false,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/e05285ca520a0cd4932bc3430024b50f893ede44.jpg",
    IsNew: true,
    Title: "7kg Mixed Frozen Free-Flow Meat Pack - North Island Delivery Only",
    Provider: "",
    City: null,
    BuyingTimes: 48,
    price: 110,
    button: false,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/47ee88627e3b3d689446c3d0de36c6ad9aa51e85.jpg",
    IsNew: false,
    Title: "60-Minute Massage Session",
    Provider: "Bamboo Spa Henderson",
    City: location[0],
    BuyingTimes: 13,
    price: 55,
    button: false,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/e08919ba66dd006f4ac75e2ef2d98a69f226cbca.jpg",
    IsNew: true,
    Title: "Frozen Coldstream Lamb",
    Provider: "",
    City: null,
    BuyingTimes: 20,
    price: 90,
    button: false,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/5f34b59c569b835477cd041783463da3e94106b3.jpg",
    IsNew: false,
    Title:
      "5-Hour Auckland Wine Tour for One Person incl. Three-Course Lunch & Drink - Options for Two, Four, Six & Eight People",
    Provider: "Auckland Scenic Tours Ltd",
    City: location[0],
    BuyingTimes: "",
    price: 139,
    button: false,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/c654a0fc9148883dd38a3485868bbed9461c6367.jpg",
    IsNew: false,
    Title: "75-Minute Pamper Package with Hot Stone Massage & Relaxing Facial",
    Provider: "Skinmatic Clinic",
    City: "Albany",
    BuyingTimes: 3,
    price: 109,
    button: false,
  },
  {
    id: id++,
    Category: category[10],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/1901224f8fa6be3994a2e3c962188b1d1c08cc06.jpg",
    IsNew: false,
    Title:
      "75-Minute Certified Teeth Whitening incl. Consult & Aftercare - Option for 90-Minute Treatment incl. A Take Home Kit",
    Provider: "Sparklewhite - Mt Wellington",
    City: location[1],
    BuyingTimes: "",
    price: 149,
    button: false,
  },
  {
    id: id++,
    Category: category[7],
    Image: "https://mediacdn.grabone.co.nz/asset/HzalVebk22",
    IsNew: false,
    Title: "Work from Home",
    Provider: "Multiple deals",
    City: null,
    BuyingTimes: "",
    price: "",
    button: true,
  },
  {
    id: id++,
    Category: category[7],
    Image: "https://mediacdn.grabone.co.nz/asset/YugEJF3paH",
    IsNew: false,
    Title: "Tasty Tipples",
    Provider: "Multiple deals",
    City: null,
    BuyingTimes: "",
    price: "",
    button: true,
  },
  {
    id: id++,
    Category: category[7],
    Image: "https://mediacdn.grabone.co.nz/asset/hWVk2iGGpA",
    IsNew: false,
    Title: "Health & wellbeing",
    Provider: "Multiple deals",
    City: null,
    BuyingTimes: "",
    price: "",
    button: true,
  },
  {
    id: id++,
    Category: category[7],
    Image: "https://mediacdn.grabone.co.nz/asset/zSWtZxlOH2",
    IsNew: false,
    Title: "Everyday Essentials Delivery",
    Provider: "Multiple deals",
    City: null,
    BuyingTimes: "",
    price: "",
    button: true,
  },
  {
    id: id++,
    Category: category[9],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/713d82d6b4ac1da73019ddedc6dbf9d60291ea83.jpg",
    IsNew: false,
    Title: "One-Night Wellington Weekend Stay for Two Adults in a Classic King Room incl. Breakfast, Welcome Drinks on Arrival, Gym Access to City Fitness Thorndon, 20% off Food & Beverages",
    Provider: "Atura Wellington",
    City: "Thorndon",
    BuyingTimes: "",
    price: "364",
    button: false,
  },
  {
    id: id++,
    Category: category[9],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/a3c912cb9f2b24036e8d6315fd775511699a82b8.jpg",

    IsNew: true,
    Title:
      "One-Night Wellington Weekend Stay for Two Adults in a Classic King Room incl. Breakfast, Welcome Drinks on Arrival, Gym Access to City Fitness Thorndon, 20% off Food & Beverages, Early Check-In & Late Check-Out - Options for Two or Three Nights",
    Provider: "Terrace Downs Resort",
    City: location[7],
    BuyingTimes: "9",
    price: "145",
    button: false,
  },
  {
    id: id++,
    Category: category[9],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/14c60688f3000ec6a1230fbb12d4a6a2d3851e81.jpg",

    IsNew: true,
    Title:
      "One-Night 5-Star Luxury Canterbury Getaway for Two incl. Two-Course Dinner, Bubbles on Arrival, Daily Breakfast, 20% off a Round of Golf, Early Check-In & Late Check-Out - Options for Four People or Family & Two-Night Stays Available",
    Provider: "Picton Yacht Club",
    City: "Picton",
    BuyingTimes: "140",
    price: "379",
    button: false,
  },
  {
    id: id++,
    Category: category[9],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/a3c912cb9f2b24036e8d6315fd775511699a82b8.jpg",
    IsNew: true,
    Title:
      "One-Night Picton Yacht Club Getaway for Two People incl. Daily Cooked Breakfast with Barista Coffee, Early Check-In & Check-Out, & 20% off Food & Beverages - Options for Two or Three Nights",
    Provider: "Kapiti Island Nature Tours",
    City: location[1],
    BuyingTimes: "163",
    price: "99",
    button: false,
  },
  {
    id: id++,
    Category: category[0],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/45a85533a44516a2be0beee912c336585b3e11b6.jpg",
    IsNew: false,

    Title:
      "Football Birthday Party For Up to 10 Children - Options for Rookie, Pro or All Star Packages",
    Provider: "FootballFix Albany",
    City: "Albany",
    BuyingTimes: "",
    price: "99",
    button: false,
  },
  {
    id: id++,
    Category: category[0],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/a1004e2ecd0a2c2676da65e962d9387a0a53caca.jpg",
    IsNew: true,
    Title: "Portable Camping Shower with Foot Pump",
    Provider: "",
    City: location[1],
    BuyingTimes: "",
    price: "88",
    button: false,
  },
  {
    id: id++,
    Category: category[0],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/b9482ac1bb587459e1ab17030ecd969184d50082.jpg",
    IsNew: false,
    Title:
      "Per-Person, Twinshare, Three-Day Abel Tasman Kayak & Walk incl. All Meals & Accommodation",
    Provider: "Wilsons Abel Tasman",
    City: location[1],
    BuyingTimes: "50",
    price: "1200",
    button: false,
  },
  {
    id: id++,
    Category: category[0],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/7f952f81db8a05eacaacecedc7cee00ec27c3ba8.jpg",
    IsNew: true,
    Title: "Inflatable Sleeping Mat",
    Provider: "",
    City: null,
    BuyingTimes: "9",
    price: "54",
    button: false,
  },
  {
    id: id++,
    Category: category[19],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/40373ed3126e39ae3f868c7cc6311eab52123b9e.jpg",
    IsNew: false,

    Title: "Six Bottle French Red Wine Selection Case",
    Provider: "Glengarry Wines Ltd",
    City: null,
    BuyingTimes: "2",
    price: "",
    button: false,
  },
  {
    id: id++,
    Category: category[19],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/68d21cb51010ee9368d831f0f1b92ce70beecf74.jpg",
    IsNew: false,
    Title:
      "Refurbished Apple iPhone 7 Plus 32GB - Four Colours Available & Option for 128GB",
    Provider: "Urban Global Ltd",
    City: null,
    BuyingTimes: "",
    price: "429",
    button: false,
  },
  {
    id: id++,
    Category: category[19],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/087758d74874f7b21423cb2c9805d73a9347a127.jpg",
    IsNew: true,
    Title: "Silk Filled Eco-Lux Duvet ",
    Provider: "",
    City: "Bdirect",
    BuyingTimes: "2",
    price: "106",
    button: false,
  },
  {
    id: id++,
    Category: category[19],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/4d702b0291a4de5634668931fc364d21d6dda7f0.jpg",
    IsNew: false,
    Title:
      "Set of Printer Cartridges Compatible with HP, Brother, Epson & Canon Printers",
    Provider: "",
    City: null,
    BuyingTimes: "1",
    price: "29",
    button: false,
  },
  {
    id: id++,
    Category: category[17],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/6c864b16526887b82d11b716a28b5b079630ff44.jpg",
    IsNew: false,
    Title: "European Dining Experience",
    Provider: "Monsieur Madame",
    City: "Mount Eden",
    BuyingTimes: "28",
    price: "79",
    button: false,
  },
  {
    id: id++,
    Category: category[17],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/76d0353d963dce827bf50f461dfc617b340097e8.jpg",
    IsNew: false,
    Title: "Any Two Eden Bistro Pizzas",
    Provider: "Eden Bistro",
    City: null,
    BuyingTimes: "2",
    price: "24.5",
    button: false,
  },
  {
    id: id++,
    Category: category[17],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/b9482ac1bb587459e1ab17030ecd969184d50082.jpg",
    IsNew: false,
    Title:
      "Watergarden Entry For Two Adults incl. 10% off Food & Drinks at The Frog & Lily Cafe - Options for One Child or Family of up to Five People",
    Provider: "Wrights Water Garden &The Frog and Lily",
    City: null,
    BuyingTimes: "20",
    price: "8",
    button: false,
  },
  {
    id: id++,
    Category: category[3],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/f218f3916c20a8e87b0c1bbd19cf09ab1c0c7b7a.jpg",
    IsNew: false,
    Title: "Fabulous Eye Trio",
    Provider: "Priya's Hair & Beauty Salon",
    City: "Browns Bay",
    BuyingTimes: "",
    price: "39",
    button: false,
  },
  {
    id: id++,
    Category: category[3],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/256c0ffbba24bc4b0f752b7b07663f00639b4b6e.jpg",
    IsNew: false,
    Title:
      "One Session of Dermapen Microneedling with Vitamin Infusion & LED - Options to incl. Dermaceuticals Uber Peel & Three Sessions",
    Provider: "Skin & Brows Studio",
    City: null,
    BuyingTimes: "",
    price: "120",
    button: false,
  },
  {
    id: id++,
    Category: category[3],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/f464818e95e46f940fa46f6f9103906a792f91e2.jpg",
    IsNew: false,
    Title: "Full Set of Classic Eyelash Extensions - Option for Volume Lashes",
    Provider: "La Bises Beauty Salon",
    City: null,
    BuyingTimes: "7",
    price: "59",
    button: false,
  },
  {
    id: id++,
    Category: category[3],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/ccc53c4147fd2430f84d1bf6ec792ad6448680a3.jpg",
    IsNew: false,
    Title: "Adjustable Eyebrow Stencil",
    Provider: "",
    City: null,
    BuyingTimes: "2",
    price: "19",
    button: false,
  },
  {
    id: id++,
    Category: category[15],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/942c181740f423d5579b631dd9dc4790ca434b45.jpg",
    IsNew: false,
    Title: "LED Solar Shadow Lamp - Two Options Available",
    Provider: "",
    City: null,
    BuyingTimes: "8",
    price: "18",
    button: false,
  },
  {
    id: id++,
    Category: category[15],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/7542f58b65c32370361ee72dcd270f753a53939f.jpg",
    IsNew: false,

    Title: "Hand Blender Kitchen Tool - Three Colours Available",
    Provider: "",
    City: null,
    BuyingTimes: "2",
    price: "40",
    button: false,
  },
  {
    id: id++,
    Category: category[15],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/410f3d3823df1e3b77b22a35fc76089050fe521b.jpg",
    IsNew: false,
    Title: "Moss, Mould & Lichen Roof Treatment",
    Provider: "Kleanfreaks",
    City: location[0],
    BuyingTimes: "3",
    price: "255",
    button: false,
  },
  {
    id: id++,
    Category: category[15],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/f974067ef30fb596146d5c7ae96ab14e73e92caf.jpg",
    IsNew: true,
    Title: "Crystal Sun Catcher",
    Provider: "",
    City: null,
    BuyingTimes: "7",
    price: "34",
    button: false,
  },
  {
    id: id++,
    Category: category[11],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/93b2fdc0de7bd59838fc418af91344657cca8592.jpg",
    IsNew: true,
    Title: "Digital Pocket Golf Range Finder",
    Provider: "",
    City: null,
    BuyingTimes: "4",
    price: "30",
    button: false,
  },
  {
    id: id++,
    Category: category[11],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/0b23e0bc966f72e0857182d8a3d230a9d9410dfb.jpg",
    IsNew: false,
    Title: "Pilates/Yoga Mat with Alignment Marks - Four Colours Available",
    Provider: "",
    City: null,
    BuyingTimes: "27",
    price: "23",
    button: false,
  },
  {
    id: id++,
    Category: category[11],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/6ffe55a9ccefcc1c50f4980f26692b96341a8a3a.jpg",
    IsNew: true,
    Title: "Electroplated Aluminium Bike Pedals",
    Provider: "",
    City: null,
    BuyingTimes: "",
    price: "36",
    button: false,
  },
  {
    id: id++,
    Category: category[11],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/bbc2f149e818204486de60ef2497acfa2a29e791.jpg",
    IsNew: true,
    Title: "Adjustable Dumbbell 40KG",
    Provider: "TSB Living",
    City: null,
    BuyingTimes: "7",
    price: "290",
    button: false,
  },
  {
    id: id++,
    Category: category[1],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/3b0082cc128d29b5c5b1c8f141dd54d035140613.jpg",
    IsNew: false,
    Title: "Super Valet Car Clean - Mobile Service",
    Provider: "Carpet & Car Cleaning Valet Service",
    City: location[0],
    BuyingTimes: "95",
    price: "79",
    button: false,
  },
  {
    id: id++,
    Category: category[1],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/19ce6981252f539115724c075c4235032844cf24.jpg",
    IsNew: true,
    Title:
      "High-Pressure Car Foam Washer - Two Colours Available - Option for One or Two",
    Provider: "",
    City: null,
    BuyingTimes: "34",
    price: "24",
    button: false,
  },
  {
    id: id++,
    Category: category[1],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/3f1336086d9f157981d5aa7878fdb1891baf603f.jpg",
    IsNew: false,
    Title:
      "Two-Pack of Car Boot Organiser Storage Bags - Two Colours Available",
    Provider: "",
    City: null,
    BuyingTimes: "61",
    price: "18",
    button: false,
  },
  {
    id: id++,
    Category: category[1],
    Image:
      "https://main-cdn.grabone.co.nz/goimage/325x225/abfe4ed2e8628c2dc387e559911f3ae85fb03987.jpg",
    IsNew: false,
    Title: "Car Lumbar Back Support",
    Provider: "",
    City: null,
    BuyingTimes: "3",
    price: "29",
    button: false,
  },
];

module.exports = {
  location,
  category,
  merchandise,
};
